media:
  input: assets/images
  output: /assets/images
  categories: [image]

content:
  - name: site_config
    label: Site Settings
    type: file
    path: _config.yml
    format: yaml
    fields:
      - name: title
        label: Site title
        type: string
        required: true
      - name: description
        label: Site description
        type: text
      - name: timezone
        label: Timezone
        type: string
        default: UTC
      - name: email
        label: Contact email
        type: string

  - name: home
    label: Home Page
    type: file
    path: index.html
    format: yaml-frontmatter
    fields:
      - name: layout
        type: string
        default: default
        hidden: true
      - name: title
        type: string
        required: true
      - name: description
        type: text
      - name: navigation_weight
        type: number
      - name: menu_style
        type: string
      - name: background
        type: string
      - name: body
        label: Page content
        type: text

  - name: blog_page
    label: Blog Page
    type: file
    path: blog.html
    format: yaml-frontmatter
    fields:
      - name: layout
        type: string
        default: default
        hidden: true
      - name: title
        type: string
        required: true
      - name: description
        type: text
      - name: navigation_weight
        type: number
      - name: body
        label: Page content
        type: text

  - name: work_page
    label: Work Page
    type: file
    path: work.html
    format: yaml-frontmatter
    fields:
      - name: layout
        type: string
        default: default
        hidden: true
      - name: title
        type: string
        required: true
      - name: description
        type: text
      - name: navigation_weight
        type: number
      - name: body
        label: Page content
        type: text

  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    filename: '{year}-{month}-{day}-{primary}.md'
    format: yaml-frontmatter
    view:
      primary: title
      fields: [title, date, categories, image]
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: layout
        type: string
        default: posts
        hidden: true
      - name: title
        type: string
        required: true
      - name: date
        type: date
      - name: published
        type: boolean
      - name: image
        type: image
        description: Featured image shown on the blog list page.
      - name: categories
        type: string
        list: true
      - name: excerpt_separator
        type: string
        description: Marker used by Jekyll to split excerpts.
      - name: body
        type: text

  - name: work_items
    label: Work Items
    type: collection
    path: _work
    filename: '{primary}.md'
    format: yaml-frontmatter
    view:
      primary: title
      fields: [title, categories, style, image]
      sort: [title, style]
      default:
        sort: title
        order: asc
    fields:
      - name: layout
        type: string
        default: work
        hidden: true
      - name: title
        type: string
        required: true
      - name: image
        type: image
        description: Thumbnail image for the portfolio grid.
      - name: style
        type: string
        required: true
        description: CSS class/id used by the work listing grid.
      - name: categories
        type: string
        list: true
      - name: body
        type: text

settings:
  content:
    merge: true
